### ISSUE TITLE
Error message in embedCells

### ISSUE THREAD

**Issue by MikhaelManurung** [KrishnaswamyLab/phemd#2]
Hi, I am trying to use the package for CyTOF data analysis. When I am running the `plotEmbedding` function, I got the following message:

```
Error in seq.int(0, 1, length.out = n) : 
  'length.out' must be a non-negative number
In addition: Warning message:
In max(state_labels) : no non-missing arguments to max; returning -Inf
```

What would be the cause of the problem?

**Comment by wschen** [comment]
Which method are you using to generate your cell-state embedding (Monocle2, PHATE, Seurat?) You would need to run the _embedCells_ and, in the case of Monocle2, _orderCellsMonocle_ functions before plotEmbedding.
