### ISSUE TITLE
import data from 10x Genomics experiments

### ISSUE THREAD

**Issue by sdwien** [KrishnaswamyLab/phemd#3]
I would like to use phemd on data we generated with the 10x Genomics Visium Spatial Transcriptomics platform.
Would you have any guidelines or code on how to import the expression data into R in order to have them in the right format for phemd?

Some of the files output by the 10x software spaceranger (or also by the single cell analysis tool cellranger) are the following:

Outputs:
- Run summary HTML:                        web_summary.html
- Run summary CSV:                         metrics_summary.csv
- BAM:                                      possorted_genome_bam.bam
- BAM index:                             possorted_genome_bam.bam.bai
- Filtered feature-barcode matrices HDF5:  filtered_feature_bc_matrix.h5
- Unfiltered feature-barcode matrices HDF5: raw_feature_bc_matrix.h5
- Per-molecule read information:           molecule_info.h5
- Loupe Browser file:                       cloupe.cloupe

Can any of these files be read by phemd or imported by another tool so that they can be read?

Many thanks for your help, and looking forward to using this interesting tool.
Best, Sophia

**Comment by wschen** [comment]
Hi Sophia,

Unfortunately PhEMD has not yet been optimized for the output of 10X Visium spatial transcriptomics data. However, I imagine the readout of spatial transcriptomics data are mean expression values of various markers for each region of interest (which contains one or a few cells). I could imagine an adapted PhEMD approach in which you treat each of these ROIs as a "cell," and could apply the PhEMD pipeline as such (i.e. identify "cell" subtypes, compute relative abundances in each specimen, generate PhEMD embedding). Note that this would not directly incorporate the spatially-resolved nature of these ROIs, but still may be interesting as an approach to compare specimens.
